  # Aliases

alias sethost="hostnamectl set-hostname"

alias ls="lsd"
alias lsh="lsd -a"
alias nftch="fastfetch"
alias pacdel="sudo pacman -R"
alias pacins="sudo pacman -S"
alias pacupt="sudo pacman -Syu"
alias checknet="ping 8.8.8.8"
alias srm="sudo rm -rf"
alias g="git"
alias gc="git clone"
alias whatismyport="ip route get 8.8.8.8 | sed -n 's/.*dev \([^\ ]*\).*/\1/p'"
alias ...="cd ../.."
alias ..="cd .."
alias .="cd ."
alias ~="cd ~/"
alias cp="cp -r"
alias cpr="fcp"
alias clr="clear"
alias syslink="ln -s"
alias screenshot="flameshot gui"
alias play="mpv $1 -wid $(xdotool getactivewindow)"
alias poweroff="sudo shutdown -h now"
alias rofi="rofi -drun-use-desktop-cache -show run -sorting-method fzf -sort"
